"""empty message

Revision ID: 8b67d0dbd75b
Revises: 3aa9af5ad20a
Create Date: 2022-02-17 16:48:18.299476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b67d0dbd75b'
down_revision = '3aa9af5ad20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=22),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
